backend:
  name: git-gateway

  collections: # A list of collections the CMS should be able to edit
  - name: 'projects' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Projects' # Used in the UI, ie.: "New Post"
    folder: 'content/projects' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Alt_text', name: 'alt_text', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Tech_used', name: 'tech_used', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Categories', name: 'categories', widget: 'list' }